defaults:
  - benchmarks
  - experiment: object_recognition
  - experiment_config: eval
  - logging: eval_benchmark
  - monty_config: evidence_1lm_dist_noise
  - env_interface_config: habitat_1sensor_distance
  - eval_env_interface_args: 10_distinct_random
  - _self_

episodes: all
num_parallel: 16
print_cfg: false
quiet_habitat_logs: true
