# @package _global_
defaults:
  - /experiment/experiment_class: object_recognition
  - /experiment/experiment_args: eval
  - /experiment/logging: eval_benchmark
  - /monty: evidence_1lm_surf_ci
  - /environment/env_interface_config: habitat_1sensor_surface
  - /environment/eval_env_interface_args: 10_distinct_predefined

experiment:
  config:
    n_eval_epochs: ${benchmarks.rotations_all_count}
