# @package _global_
defaults:
  - /experiment/experiment_args: unsupervised_train
  - /experiment/logging: training_detailed
  - /monty: evidence_1lm_surf_unsupervised_train
  - /environment/env_interface_config: habitat_1sensor_surface
  - /environment/train_env_interface_args: 10_distinct_random
  - /environment/eval_env_interface_args: 10_distinct_predefined
  - /experiment/experiment_class: object_recognition

experiment:
  config:
    max_train_steps: 4000
    max_total_steps: 4000
    n_train_epochs: 10
    logging:
      run_name: surf_agent_unsupervised_10distinctobj_noise
      python_log_level: INFO
      wandb_group: debugging
    monty_config:
      motor_system_config:
        motor_system_args:
          policy:
            _target_: tbp.monty.frameworks.models.motor_policies.SurfacePolicy
      sensor_module_configs:
        sensor_module_0:
          sensor_module_args:
            noise_params: ${benchmarks.default_all_noise_params}
      learning_module_configs:
        learning_module_0:
          learning_module_args:
            graph_delta_thresholds:
              patch:
                distance: 0.01
                pose_vectors: ${np.list_eval:[np.pi / 8, np.pi * 2, np.pi * 2]}
                principal_curvatures_log:
                - 1.0
                - 1.0
                hsv:
                - 0.1
                - 1
                - 1
            object_evidence_threshold: 100
            required_symmetry_evidence: 20
            x_percent_threshold: 50
            hypotheses_updater_args:
              max_nneighbors: 5
